### ISSUE TITLE
trezor hardware wallet transfers fail.

### ISSUE THREAD

**Issue by jimscarver** [tgrospic/rnode-client-js#22]
metamask is the only way hardware wallet users can access their rev. There mave been many complaints from trezor users. trezor transfers usually fail using the rchain client page with metamask. A work around I found is to copy the deploy code from metamask and do a custom deploy https://youtu.be/i0E1L_zHPmQ

**Comment by tgrospic** [comment]
@jimscarver Thanks for detailed info. Can you please try, instead of copying to _custom deploy_ just run transaction again. This should be basically the same action.

Also what happens when you try to execute two transactions in a row.

**Comment by jimscarver** [comment]
trying  transfer and number of times before or after a custom deploy never works. A trezor screen pops up and dissapears without asking you to hit the button on the device and gets stuck at "Deploying..."

The custom deploy always asks you to hit the button on the trezor to confirm the transaction. and succeeds.

**Comment by tgrospic** [comment]
Thanks @jimscarver for great help to diagnose the problem.

What we found is the problem with leading whitespaces in Rholang code which makes Trezor to skip the confirmation step after Metamask _sign_ dialog. The problem is visible when 7 or more whitespace characters are in the start of the line.

The fix is to remove all leading whitespace characters from transfer contract (https://github.com/tgrospic/rnode-client-js/commit/4ec4dac9314d5971187def2a3a64309a1d29c96b).
