### ISSUE TITLE
allow caller to supply fetch to getDataForDeploy, rnodeHttp

### ISSUE THREAD

**Issue by dckc** [tgrospic/rnode-client-js#6]
https://github.com/tgrospic/rnode-client-js/blob/72931bedd2c66cc83e437f34f9ab7f3a8a0ba76f/src/rnode-web.js#L149

**Comment by tgrospic** [comment]
@dckc are you suggesting to make something similar what you did in rv2020?
https://github.com/rchain-community/rv2020/blob/ff615d3/webui/public/index.html#L84

I'm wondering how much this can be enforced in today's browsers.

**Comment by dckc** [comment]
Google Caja was in production enforcing object capability discipline in browsers as far back as 2008. (And it's still in production; see [ocap libraries and frameworks](https://github.com/dckc/awesome-ocap#libraries-and-frameworks)).

But whether browsers enforce object capability discipline is independent of whether the discipline itself is a sound engineering practice.

Look at it this way: what would you do if someone asked you to make a unit test for `getDataForDeploy` or `rnodeHttp`? You'd be stuck, right? There's no way to invoke it without it using the real browser `fetch`; you'd have to make some integration test where you rig up a testing network, in addition to including a whole browser in your unit test harness. So yes, I'm suggesting passing the `fetch` capability around explicitly as in `index.html` and [rgate.js](https://github.com/rchain-community/rv2020/blob/ff615d34299a8d949dfd3fc6db754307e62e329b/webui/src/rgate.js). This way, unit testing is straightforward: you just provide a mock `fetch`. Maybe you've heard of it as the [Hollywood Principle](https://wiki.c2.com/?HollywoodPrinciple), "_Don't call us, we'll call you_".

**Comment by dckc** [comment]
I rephrased the title as an enhancement, following the label.

**Comment by tgrospic** [comment]
@dckc I made some refactoring of the web example to extract DOM dependencies as input parameters. _index.js_ is an entry point where DOM is accessed and supplied to the UI part.
This is still not completely true because Metamask API depends on [window.ethereum](https://github.com/tgrospic/rnode-client-js/blob/d903275/src/eth/eth-wrapper.js#L7) which is like free variable in eth-wrapper.

https://github.com/tgrospic/rnode-client-js/blob/c129cc3dec2f1d20eed17a002880388ec10ff154/src/web/index.js#L7-L27

I haven't followed what was happening with Caja but now it's interesting to explore it more.
Examples in the playground seems to have some loading problems (?).
https://developers.google.com/caja/docs/playground

Why not just start to use `harden` to freeze input dependencies?

**Comment by dckc** [comment]
briefly...

> Why not just start to use `harden` to freeze input dependencies?

because the caller might not expect the data they passed in to become hardened.

**Comment by dckc** [comment]
> @dckc I made some refactoring of the web example to extract DOM dependencies as input parameters. _index.js_ is an entry point where DOM is accessed and supplied to the UI part.

Yay!

That addresses this issue to my satisfaction.
